### ISSUE TITLE
'Message' has no attribute '__base__'

### ISSUE THREAD

**Issue by sasilva1998** [mgtm98/uRos#1]
Hi, I was trying out your lib, and can't go through an error I am having, it is the following:

```
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "uros/core.py", line 158, in publish
AttributeError: type object 'Message' has no attribute '__base__'
```
was checking the code and as said there, it actually has no `__base__` attribute, is there something I am missing? Thank you in advance.

**Comment by mgtm98** [comment]
Thank you for your interest, there was some bugs in the code i fixed it in my local branch but forgot to push them. 
I fixed this issue and i'm happily waiting for your feedback.

**Comment by sasilva1998** [comment]
I am no longer getting any error, however, I am trying the examples you suggested in the README and no topic is advertised, I mean even when I subscribe or publish, the topic done this to doesn't appear by using `rostopic list`, I do get my ESP32 connected as a client to rosbridge tho.
